### ISSUE TITLE
Stage 2 - Review requirements checklist

### ISSUE THREAD

**Issue by JeremieLitzler** [JeremieLitzler/mws-restaurant-stage-2#6]
# Application Data and Offline Use

## Application Data Source

- [ ] The client application should pull restaurant data from the development server, parse the JSON response, and use the information to render the appropriate sections of the application UI.

## Offline Use

- [ ] The client application works offline. JSON responses are cached using the IndexedDB API. Any data previously accessed while connected is reachable while offline.

# Responsive Design and Accessibility

## Responsive Design

- [ ] The application maintains a responsive design on mobile, tablet and desktop viewports.

## Accessibility

- [ ] The application retains accessibility features from the Stage 1 project. Images have alternate text, the application uses appropriate focus management for navigation, and semantic elements and ARIA attributes are used correctly.

# Performance

# Site Performance

- [ ] Lighthouse targets for each category exceed:
  - [ ] Progressive Web App: >90
  - [ ] Performance: >70 
  - [ ] Accessibility: >90
